flowchart TD
    classDef entity fill:#e1f5fe,stroke:#01579b,stroke-width:2px,color:#000
    classDef attr fill:#fff9c4,stroke:#fbc02d,stroke-width:1px,color:#000

    ePayment[PAYMENT]:::entity

    aPk([payment_id PK]):::attr
    aAppFk([appointment_id FK]):::attr
    aAmt([amount]):::attr
    aDate([payment_date]):::attr
    aMethod([payment_method]):::attr
    aStatus([status]):::attr

    ePayment --- aPk
    ePayment --- aAppFk
    ePayment --- aAmt
    ePayment --- aDate
    ePayment --- aMethod
    ePayment --- aStatus
